package com.hers.robinet.tfe.descriptor;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;


public class AttributeDescriptor extends RelationDescriptor{
	
	public AttributeDescriptor(Field attribute)
	{
		String name=null;
		for (Annotation annotation : attribute.getAnnotations()){
			if(annotation instanceof javax.persistence.Column)
			{
				name = ((javax.persistence.Column) annotation).name();
				if (name == "")
				{
					name = null;
				}
				isnullable = ((javax.persistence.Column) annotation).nullable();
				isUnique = ((javax.persistence.Column) annotation).unique();
			}
			else if (annotation instanceof javax.persistence.Id)
			{
				isId = true;
			}
			else if (annotation instanceof javax.persistence.GeneratedValue){
				if (attribute.getType() == Integer.class)
				{
					isAutoGenerated = true;
					isId = true;
				}
				else{
					throw new ModelRuntimeException("@GeneratedValue can only be use on Integer");
				}
			}
		}
		
		if(name == null)
			name = attribute.getName();
		
		typeStruct.add(new TypeDescriptor(attribute, name, attribute.getType()));
	}
}
