package com.hers.robinet.tfe.jpaHelper;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;

import com.hers.robinet.tfe.dbGenerator.SchemaDB;
import com.hers.robinet.tfe.dialect.Dialect;
import com.hers.robinet.tfe.mananger.DbManager;

/**
 * supported annotation:
 * @Table(name="tableName",
 * 		indexes = {@Index(name = "my_index_name",  columnList="iso_code"),
                  @Index(name = "my_index_name2", columnList="name, colum2")})
 */
public class JpaClass{
	
	public static String getIdentifiantNameFromClass(Class<?> type){
		return type.getName();
	}
	
	private Class<?> type;
	private String identifiantName;
	private String name;
	private ArrayList<JpaIndex> indexes = new ArrayList<JpaIndex>();
	private ArrayList<JpaRelation> attributes = new ArrayList<JpaRelation>();
	private ArrayList<JpaRelation> ids = new ArrayList<JpaRelation>();
	private ArrayList<JpaRelation> fks = new ArrayList<JpaRelation>();
	
	private PreparedStatement insert = null;
	private PreparedStatement update = null;
	private PreparedStatement delete = null;
	
	public Class<?> getType() {
		return type;
	}

	public String getName() {
		return name;
	}

	public ArrayList<JpaIndex> getIndexes() {
		return indexes;
	}

	public ArrayList<JpaRelation> getAttributes() {
		return attributes;
	}

	public ArrayList<JpaRelation> getIds() {
		return ids;
	}

	public ArrayList<JpaRelation> getFks() {
		return fks;
	}

	public String getIdentifiantName() {
		return identifiantName;
	}
	
	public JpaClass(Class<?> type, SchemaDB schema)
	{
		this.type = type;

		name = null;
		for (Annotation annotation : type.getAnnotations())
			if(annotation instanceof javax.persistence.Table){
				name = ((javax.persistence.Table) annotation).name();
				if (name =="")
					name=null;
				for (javax.persistence.Index index : ((javax.persistence.Table) annotation).indexes()) {
					indexes.add(new JpaIndex(index));
				}
			}
				
		if(name == null)
			name = type.getSimpleName();
		identifiantName = getIdentifiantNameFromClass(type);
		
		int generatedValueCount = 0;
		for (Field attribute : type.getDeclaredFields()) {
			JpaRelation temp = JpaRelation.getAttribute(attribute, this, schema);
			
			if (temp != null)
			{
				if(temp.isAutoGenerated()){
					++generatedValueCount;
					if(generatedValueCount>1)
						throw new ModelException("A table can only have one @GeneretedValue");
				}
				
				if(temp.isId() && !temp.isAbstract)
				{
					ids.add(temp);
				}
				
				if(temp.getRelationType() != DbManager.noRelation)
				{
					fks.add(temp);
				}
				
				attributes.add(temp);
			}
		}
	}
	
	public JpaClass(JpaClass table1, JpaClass table2)
	{
		identifiantName = "FILL_"+table1.getIdentifiantName()+"_"+table2.getIdentifiantName();
		name="FILL_"+table1.getName()+"_"+table2.getName();
		

		JpaRelationManyToOne att1 = new JpaRelationManyToOne(table1);
		JpaRelationManyToOne att2 = new JpaRelationManyToOne(table2);
		attributes.add(att1);
		attributes.add(att2);
		ids = attributes;
		fks = attributes;
		
	}
	
	public void generatePrepareStatement(Connection connection, Dialect dialect)
	{
		connection.prepareStatement("");
	}
	
	public 
	
	
	
	
	
	

}
