package jpaHelper;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.NoSuchElementException;

import com.hers.robinet.tfe.dbGenerator.SchemaDB;
import com.hers.robinet.tfe.mananger.DbManager;

/**
 * Represent a attribute.
 * Supported annotation:
 * 	@column name, nullable, unique
 *  @id
 *  @GeneretedValue (on Integer, unique for the table. Id can be ommited for this attribute)
 *  @OneToOne, @OneToMany, @ManyToOne, @ManyToMany
 *  @Transient
 */
public abstract class JpaRelation {

	protected ArrayList<JpaType> typeStruct = new ArrayList<JpaType>();
	protected boolean isAutoGenerated = false;
	protected boolean isId = false;
	protected boolean isnullable = false;
	protected boolean isUnique = false;
	protected boolean isAbstract = false;
	protected int relationType = DbManager.noRelation;
	
	
	public static JpaRelation getAttribute(Field attribute, JpaClass tableClass, SchemaDB schema)
	{
		int relationType = DbManager.noRelation;
		for (Annotation annotation : attribute.getAnnotations()){
			if (annotation instanceof javax.persistence.Transient)
			{
				return null;
			}
			
			if (!DbManager.isPrimaryType(attribute.getType()))
			{
				if (annotation instanceof javax.persistence.OneToOne){
					relationType = DbManager.OneToOne;
				}
				else if (annotation instanceof javax.persistence.ManyToOne){
					relationType = DbManager.ManyToOne;
				}
				else if (annotation instanceof javax.persistence.OneToMany){
					relationType = DbManager.OneToMany;
				}
				else if (annotation instanceof javax.persistence.ManyToMany){
					relationType = DbManager.ManyToMany;
				}
				else{
					throw new ModelException("A class which is not a primitive type(cf:doc) should have a relation");
				}
			}
		}
		
		if(relationType == DbManager.noRelation){
			return new JpaAttribute(attribute);
		}
		else if(relationType == DbManager.OneToOne){
			return new JpaRelationOneToOne(attribute, schema);
		}
		else if(relationType == DbManager.ManyToOne){
			return new JpaRelationManyToOne(attribute, schema);
		}
		else if(relationType == DbManager.OneToMany)
		{
			return new JpaRelationOneToMany(attribute, schema);
		}
		else if(relationType == DbManager.ManyToMany){
			return new JpaRelationManyToMany(attribute, schema, tableClass);
		}
		return null;
	}
	
	
	
	
	public ArrayList<JpaType> getTypeStruct() {
		return typeStruct;
	}

	public int getRelationType() {
		return relationType;
	}
	
	public boolean isAutoGenerated() {
		return isAutoGenerated;
	}

	public boolean isId() {
		return isId;
	}

	public boolean isIsnullable() {
		return isnullable;
	}

	public boolean isUnique() {
		return isUnique;
	}
	
	public boolean isAbstract()
	{
		return isAbstract;
	}
	
	public JpaClass getReferencedTable()
	{
		throw new UnsupportedOperationException();
	}
	
	public static class JpaRelationIterator implements Iterator<JpaType>
	{
		private ArrayList<JpaRelation> el;
		private int i = 0;
		private int innerI = 0;
		
		public JpaRelationIterator(ArrayList<JpaRelation> el)
		{
			this.el = el;
		}
		
		public boolean hasNext() {
			
			
			if (i<el.size())
			{
				int temp = i;
				while(temp<el.size() && el.get(temp).getTypeStruct().size()==0)
				{
					++temp;
				}
				
				
				if(i==el.size()-1 && innerI == el.get(i).getTypeStruct().size())
				{
					return false;
				}
				
				
				return temp<el.size();
			}
			return false;
		}
		
		public JpaRelation getCurrentRelation()
		{
			return el.get(i);
		}

		public JpaType next() {
			if (!hasNext()) throw new NoSuchElementException();
			while(i<el.size() && innerI >= el.get(i).getTypeStruct().size())
			{
				innerI = 0;
				++i;
			}
			
			++innerI;
			
			el.get(i);
			
			return el.get(i).getTypeStruct().get(innerI-1);
		}	
	}
}
